### ISSUE TITLE
unable to start container process: exec: "/app/bw_export.sh": permission denied: unknown.

### ISSUE THREAD

**Issue by ALERTua** [0neTX/UnRAID_Template#3]
Docker container doesn't start:
`docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/app/bw_export.sh": permission denied: unknown.`

**Comment by 0neTX** [comment]
Resolved in docker image v1.1, please check again. Thanks for your issue! >D

**Comment by ALERTua** [comment]
It works.
