### ISSUE TITLE
Files are being created with root user

### ISSUE THREAD

**Issue by 0neTX** [0neTX/UnRAID_Template#6]
@Vitor Ventura bug reported: 

Files are being created with root user, is there any way to create files, with different permissions?
Even after give permissions in template, files still being created with root and only root can read and write. 

[https://forums.unraid.net/topic/127999-support-onetx-teledock-bot-docker-control-template-support/#comment-1358017](https://forums.unraid.net/topic/127999-support-onetx-teledock-bot-docker-control-template-support/#comment-1358017)

**Comment by vmfventura** [comment]
Added this to the template, and being worked well.
Have you tried?

PUID and PGID
![image](https://github.com/0neTX/UnRAID_Template/assets/19309974/f0174b65-cbe7-451d-ba66-f308c074c7b6)

**Comment by 0neTX** [comment]
Hello 
Have you added those two variables and does it work for you? 

Yesterday I was doing tests, But don't get to a good point. 

If you only need those two variables, I'll add them to the template. 

How do you check that user 1000 has permissions to the file?

**Comment by vmfventura** [comment]
> Hello Have you added those two variables and does it work for you?
> 
> Yesterday I was doing tests, But don't get to a good point.
> 
> If you only need those two variables, I'll add them to the template.
> 
> How do you check that user 1000 has permissions to the file?

Yes i confirmed.
Added to the template, and is working.
All files are created with 666.
![image](https://github.com/0neTX/UnRAID_Template/assets/19309974/b7f98522-bca4-442e-be95-984755552bfa)

**Comment by 0neTX** [comment]
Thanks! 

I'll change the template. Thank you!!

**Comment by vmfventura** [comment]
Have you confirmed? Working?

**Comment by 0neTX** [comment]
Yesterday, I was testing and setting PUID and PGID but the files created are only accessible to the root user.

I am preparing a modified version that uses PUID and PGID correctly. I'mdoing some tests and in a few hours the new version  will be released with this feature.

**Comment by 0neTX** [comment]
I have released a new version v1.2 with this new feature. 

https://github.com/0neTX/Bitwarden_Export/pull/5

Please check the documentation and upgrade to the latest version. 

Thank you!
