### ISSUE TITLE
Request - keep 'x' number of backups 

### ISSUE THREAD

**Issue by epicfail9000** [0neTX/UnRAID_Template#7]
for bitwarden export 

Could you possibly add a way to keep the backup directory from overfilling? 

Something like these below and make them optional?

Number of days to keep backups:  x days 
Number of backups to keep:  x backups

**Comment by 0neTX** [comment]
Hi epicfail9000, 

Thank you for opening a ticker and for using the project, any suggestions or help are appreciated. 

Please refer to the "Variable KEEP_LAST_BACKUPS" section in the project documentation: 
[README](https://github.com/0neTX/Bitwarden_Export/)
This repository is for the maintenance of the Unraid template only.

Thank you
